03/10/2025 12:46:24 PM - INFO - Inicio do programa
03/10/2025 12:46:24 PM - INFO - Entrando no sspds
03/10/2025 12:46:40 PM - INFO - Transformando relatorio de FURTO em dataframe
03/10/2025 12:46:40 PM - ERROR - Houve um erro na funcao de transformar relatorios em dfs: Traceback (most recent call last):
  File "c:\Users\paulo.welton\Desktop\BOT_EXTRACAO_DADOS_SSPDS\src\model\transformar_relatorios_em_dataframes.py", line 17, in transformar_relatorios_em_dataframes
    dataframe = pd.read_excel(arquivo_xlsx)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\excel\_base.py", line 364, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\excel\_base.py", line 1191, in __init__
    ext = inspect_excel_format(
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\excel\_base.py", line 1070, in inspect_excel_format
    with get_handle(
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\common.py", line 710, in get_handle
    handle = open(handle, ioargs.mode)
OSError: [Errno 22] Invalid argument: 'C:\\Users\\<built-in function getlogin>\\Downloads\\Furto_2009-a-2024.xlsx'

03/10/2025 12:46:40 PM - INFO - Final do programa
